### ISSUE TITLE
Feature Request: Allow users to change the size of the table / photos with a %

### ISSUE THREAD

**Issue by brrees01** [matthewjdegarmo/MyTop8#1]
See the below example. It would be nice, if the table is too large for some reason, to be able to shrink (or maybe expand) the size of the table / photos with a provided %.
```yaml
name: My Top 8
on:
  schedule:
  #runs every hour
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-mytop8-section:
    name: Update this repo's README my top 8 users.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matthewjdegarmo/MyTop8@latest
        with:
          users_list: --MyspaceTom--, matthewjdegarmo, brrees01, intenseone, EdwardHanlon, endoleg, packersking, TylerLeonhardt
          table_size_percent: 75
```

This would default to 100, but can be overridden by including the table_size_percent parameter (or some other name).
